package com.dsky.baas.gameinvite.model;

public class EventConfig {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event_config.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event_config.game_id
     *
     * @mbggenerated
     */
    private Integer gameId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event_config.event_name
     *
     * @mbggenerated
     */
    private String eventName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event_config.add_points
     *
     * @mbggenerated
     */
    private Integer addPoints;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event_config.create_at
     *
     * @mbggenerated
     */
    private Integer createAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event_config.update_at
     *
     * @mbggenerated
     */
    private Integer updateAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column event_config.delete_at
     *
     * @mbggenerated
     */
    private Integer deleteAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event_config.id
     *
     * @return the value of event_config.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event_config.id
     *
     * @param id the value for event_config.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event_config.game_id
     *
     * @return the value of event_config.game_id
     *
     * @mbggenerated
     */
    public Integer getGameId() {
        return gameId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event_config.game_id
     *
     * @param gameId the value for event_config.game_id
     *
     * @mbggenerated
     */
    public void setGameId(Integer gameId) {
        this.gameId = gameId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event_config.event_name
     *
     * @return the value of event_config.event_name
     *
     * @mbggenerated
     */
    public String getEventName() {
        return eventName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event_config.event_name
     *
     * @param eventName the value for event_config.event_name
     *
     * @mbggenerated
     */
    public void setEventName(String eventName) {
        this.eventName = eventName == null ? null : eventName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event_config.add_points
     *
     * @return the value of event_config.add_points
     *
     * @mbggenerated
     */
    public Integer getAddPoints() {
        return addPoints;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event_config.add_points
     *
     * @param addPoints the value for event_config.add_points
     *
     * @mbggenerated
     */
    public void setAddPoints(Integer addPoints) {
        this.addPoints = addPoints;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event_config.create_at
     *
     * @return the value of event_config.create_at
     *
     * @mbggenerated
     */
    public Integer getCreateAt() {
        return createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event_config.create_at
     *
     * @param createAt the value for event_config.create_at
     *
     * @mbggenerated
     */
    public void setCreateAt(Integer createAt) {
        this.createAt = createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event_config.update_at
     *
     * @return the value of event_config.update_at
     *
     * @mbggenerated
     */
    public Integer getUpdateAt() {
        return updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event_config.update_at
     *
     * @param updateAt the value for event_config.update_at
     *
     * @mbggenerated
     */
    public void setUpdateAt(Integer updateAt) {
        this.updateAt = updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column event_config.delete_at
     *
     * @return the value of event_config.delete_at
     *
     * @mbggenerated
     */
    public Integer getDeleteAt() {
        return deleteAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column event_config.delete_at
     *
     * @param deleteAt the value for event_config.delete_at
     *
     * @mbggenerated
     */
    public void setDeleteAt(Integer deleteAt) {
        this.deleteAt = deleteAt;
    }
}