package com.dsky.baas.gameinvite.model;

public class GameConfig {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_config.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_config.game_id
     *
     * @mbggenerated
     */
    private Integer gameId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_config.option_name
     *
     * @mbggenerated
     */
    private String optionName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_config.option_val
     *
     * @mbggenerated
     */
    private String optionVal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_config.create_at
     *
     * @mbggenerated
     */
    private Integer createAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_config.update_at
     *
     * @mbggenerated
     */
    private Integer updateAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column game_config.delete_at
     *
     * @mbggenerated
     */
    private Integer deleteAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_config.id
     *
     * @return the value of game_config.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_config.id
     *
     * @param id the value for game_config.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_config.game_id
     *
     * @return the value of game_config.game_id
     *
     * @mbggenerated
     */
    public Integer getGameId() {
        return gameId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_config.game_id
     *
     * @param gameId the value for game_config.game_id
     *
     * @mbggenerated
     */
    public void setGameId(Integer gameId) {
        this.gameId = gameId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_config.option_name
     *
     * @return the value of game_config.option_name
     *
     * @mbggenerated
     */
    public String getOptionName() {
        return optionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_config.option_name
     *
     * @param optionName the value for game_config.option_name
     *
     * @mbggenerated
     */
    public void setOptionName(String optionName) {
        this.optionName = optionName == null ? null : optionName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_config.option_val
     *
     * @return the value of game_config.option_val
     *
     * @mbggenerated
     */
    public String getOptionVal() {
        return optionVal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_config.option_val
     *
     * @param optionVal the value for game_config.option_val
     *
     * @mbggenerated
     */
    public void setOptionVal(String optionVal) {
        this.optionVal = optionVal == null ? null : optionVal.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_config.create_at
     *
     * @return the value of game_config.create_at
     *
     * @mbggenerated
     */
    public Integer getCreateAt() {
        return createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_config.create_at
     *
     * @param createAt the value for game_config.create_at
     *
     * @mbggenerated
     */
    public void setCreateAt(Integer createAt) {
        this.createAt = createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_config.update_at
     *
     * @return the value of game_config.update_at
     *
     * @mbggenerated
     */
    public Integer getUpdateAt() {
        return updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_config.update_at
     *
     * @param updateAt the value for game_config.update_at
     *
     * @mbggenerated
     */
    public void setUpdateAt(Integer updateAt) {
        this.updateAt = updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column game_config.delete_at
     *
     * @return the value of game_config.delete_at
     *
     * @mbggenerated
     */
    public Integer getDeleteAt() {
        return deleteAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column game_config.delete_at
     *
     * @param deleteAt the value for game_config.delete_at
     *
     * @mbggenerated
     */
    public void setDeleteAt(Integer deleteAt) {
        this.deleteAt = deleteAt;
    }
}