package com.dsky.baas.gameinvite.model;

public class PointsLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column points_log_tpl.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column points_log_tpl.player_id
     *
     * @mbggenerated
     */
    private Integer playerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column points_log_tpl.game_id
     *
     * @mbggenerated
     */
    private Integer gameId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column points_log_tpl.act_id
     *
     * @mbggenerated
     */
    private Integer actId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column points_log_tpl.from_player_id
     *
     * @mbggenerated
     */
    private Integer fromPlayerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column points_log_tpl.event_name
     *
     * @mbggenerated
     */
    private String eventName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column points_log_tpl.event_args
     *
     * @mbggenerated
     */
    private String eventArgs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column points_log_tpl.after_num
     *
     * @mbggenerated
     */
    private Integer afterNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column points_log_tpl.add_num
     *
     * @mbggenerated
     */
    private Integer addNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column points_log_tpl.should_num
     *
     * @mbggenerated
     */
    private Integer shouldNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column points_log_tpl.invited_code
     *
     * @mbggenerated
     */
    private String invitedCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column points_log_tpl.create_time
     *
     * @mbggenerated
     */
    private Integer createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column points_log_tpl.id
     *
     * @return the value of points_log_tpl.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column points_log_tpl.id
     *
     * @param id the value for points_log_tpl.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column points_log_tpl.player_id
     *
     * @return the value of points_log_tpl.player_id
     *
     * @mbggenerated
     */
    public Integer getPlayerId() {
        return playerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column points_log_tpl.player_id
     *
     * @param playerId the value for points_log_tpl.player_id
     *
     * @mbggenerated
     */
    public void setPlayerId(Integer playerId) {
        this.playerId = playerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column points_log_tpl.game_id
     *
     * @return the value of points_log_tpl.game_id
     *
     * @mbggenerated
     */
    public Integer getGameId() {
        return gameId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column points_log_tpl.game_id
     *
     * @param gameId the value for points_log_tpl.game_id
     *
     * @mbggenerated
     */
    public void setGameId(Integer gameId) {
        this.gameId = gameId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column points_log_tpl.act_id
     *
     * @return the value of points_log_tpl.act_id
     *
     * @mbggenerated
     */
    public Integer getActId() {
        return actId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column points_log_tpl.act_id
     *
     * @param actId the value for points_log_tpl.act_id
     *
     * @mbggenerated
     */
    public void setActId(Integer actId) {
        this.actId = actId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column points_log_tpl.from_player_id
     *
     * @return the value of points_log_tpl.from_player_id
     *
     * @mbggenerated
     */
    public Integer getFromPlayerId() {
        return fromPlayerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column points_log_tpl.from_player_id
     *
     * @param fromPlayerId the value for points_log_tpl.from_player_id
     *
     * @mbggenerated
     */
    public void setFromPlayerId(Integer fromPlayerId) {
        this.fromPlayerId = fromPlayerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column points_log_tpl.event_name
     *
     * @return the value of points_log_tpl.event_name
     *
     * @mbggenerated
     */
    public String getEventName() {
        return eventName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column points_log_tpl.event_name
     *
     * @param eventName the value for points_log_tpl.event_name
     *
     * @mbggenerated
     */
    public void setEventName(String eventName) {
        this.eventName = eventName == null ? null : eventName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column points_log_tpl.event_args
     *
     * @return the value of points_log_tpl.event_args
     *
     * @mbggenerated
     */
    public String getEventArgs() {
        return eventArgs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column points_log_tpl.event_args
     *
     * @param eventArgs the value for points_log_tpl.event_args
     *
     * @mbggenerated
     */
    public void setEventArgs(String eventArgs) {
        this.eventArgs = eventArgs == null ? null : eventArgs.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column points_log_tpl.after_num
     *
     * @return the value of points_log_tpl.after_num
     *
     * @mbggenerated
     */
    public Integer getAfterNum() {
        return afterNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column points_log_tpl.after_num
     *
     * @param afterNum the value for points_log_tpl.after_num
     *
     * @mbggenerated
     */
    public void setAfterNum(Integer afterNum) {
        this.afterNum = afterNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column points_log_tpl.add_num
     *
     * @return the value of points_log_tpl.add_num
     *
     * @mbggenerated
     */
    public Integer getAddNum() {
        return addNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column points_log_tpl.add_num
     *
     * @param addNum the value for points_log_tpl.add_num
     *
     * @mbggenerated
     */
    public void setAddNum(Integer addNum) {
        this.addNum = addNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column points_log_tpl.should_num
     *
     * @return the value of points_log_tpl.should_num
     *
     * @mbggenerated
     */
    public Integer getShouldNum() {
        return shouldNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column points_log_tpl.should_num
     *
     * @param shouldNum the value for points_log_tpl.should_num
     *
     * @mbggenerated
     */
    public void setShouldNum(Integer shouldNum) {
        this.shouldNum = shouldNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column points_log_tpl.invited_code
     *
     * @return the value of points_log_tpl.invited_code
     *
     * @mbggenerated
     */
    public String getInvitedCode() {
        return invitedCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column points_log_tpl.invited_code
     *
     * @param invitedCode the value for points_log_tpl.invited_code
     *
     * @mbggenerated
     */
    public void setInvitedCode(String invitedCode) {
        this.invitedCode = invitedCode == null ? null : invitedCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column points_log_tpl.create_time
     *
     * @return the value of points_log_tpl.create_time
     *
     * @mbggenerated
     */
    public Integer getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column points_log_tpl.create_time
     *
     * @param createTime the value for points_log_tpl.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Integer createTime) {
        this.createTime = createTime;
    }
}