package com.dsky.baas.pointsservice.model;

public class PointsPoolGameTotal {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column points_pool_game_total.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column points_pool_game_total.player_id
     *
     * @mbggenerated
     */
    private Integer playerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column points_pool_game_total.game_id
     *
     * @mbggenerated
     */
    private Integer gameId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column points_pool_game_total.points_num
     *
     * @mbggenerated
     */
    private Integer pointsNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column points_pool_game_total.last_add_time
     *
     * @mbggenerated
     */
    private Integer lastAddTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column points_pool_game_total.id
     *
     * @return the value of points_pool_game_total.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column points_pool_game_total.id
     *
     * @param id the value for points_pool_game_total.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column points_pool_game_total.player_id
     *
     * @return the value of points_pool_game_total.player_id
     *
     * @mbggenerated
     */
    public Integer getPlayerId() {
        return playerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column points_pool_game_total.player_id
     *
     * @param playerId the value for points_pool_game_total.player_id
     *
     * @mbggenerated
     */
    public void setPlayerId(Integer playerId) {
        this.playerId = playerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column points_pool_game_total.game_id
     *
     * @return the value of points_pool_game_total.game_id
     *
     * @mbggenerated
     */
    public Integer getGameId() {
        return gameId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column points_pool_game_total.game_id
     *
     * @param gameId the value for points_pool_game_total.game_id
     *
     * @mbggenerated
     */
    public void setGameId(Integer gameId) {
        this.gameId = gameId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column points_pool_game_total.points_num
     *
     * @return the value of points_pool_game_total.points_num
     *
     * @mbggenerated
     */
    public Integer getPointsNum() {
        return pointsNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column points_pool_game_total.points_num
     *
     * @param pointsNum the value for points_pool_game_total.points_num
     *
     * @mbggenerated
     */
    public void setPointsNum(Integer pointsNum) {
        this.pointsNum = pointsNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column points_pool_game_total.last_add_time
     *
     * @return the value of points_pool_game_total.last_add_time
     *
     * @mbggenerated
     */
    public Integer getLastAddTime() {
        return lastAddTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column points_pool_game_total.last_add_time
     *
     * @param lastAddTime the value for points_pool_game_total.last_add_time
     *
     * @mbggenerated
     */
    public void setLastAddTime(Integer lastAddTime) {
        this.lastAddTime = lastAddTime;
    }
}