package com.dsky.baas.gameinvite.dao;

import com.dsky.baas.gameinvite.model.DeviceInvited;

public interface DeviceInvitedMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_invited_0
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * 通过device增加count的个数默认+1
     * @author eaves.zhu
     * @param record
     * @return
     */
    int insert(DeviceInvited record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_invited_0
     *
     * @mbggenerated
     */
    int insertSelective(DeviceInvited record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_invited_0
     *
     * @mbggenerated
     */
    DeviceInvited selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table device_invited_0
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(DeviceInvited record);

    /**
     * 通过device查询
     * @author eaves.zhu
     * @param record
     * @return
     */
    int updateByDeviceKeySelective(DeviceInvited record);

	   /**
     * 通过device查询绑定该deviceid的code的个数
     * @author eaves.zhu
     * @param record
     * @return
     */
    DeviceInvited selectByDevice(DeviceInvited record);

	

	
}