package com.dsky.baas.gameinvite.dao;

import com.dsky.baas.gameinvite.model.EventConfig;

public interface EventConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event_config
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event_config
     *
     * @mbggenerated
     */
    int insert(EventConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event_config
     *
     * @mbggenerated
     */
    int insertSelective(EventConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event_config
     *
     * @mbggenerated
     */
    EventConfig selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event_config
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(EventConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table event_config
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(EventConfig record);
}