package com.dsky.baas.gameinvite.dao;

import com.dsky.baas.gameinvite.model.IdGenerator;

public interface IdGeneratorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table id_generator
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table id_generator
     *
     * @mbggenerated
     */
    int insert(IdGenerator record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table id_generator
     *
     * @mbggenerated
     */
    int insertSelective(IdGenerator record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table id_generator
     *
     * @mbggenerated
     */
    IdGenerator selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table id_generator
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(IdGenerator record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table id_generator
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(IdGenerator record);
}