package com.dsky.baas.gameinvite.dao;

import com.dsky.baas.gameinvite.model.InvitedCode;

public interface InvitedCodeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invited_code_0
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(InvitedCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invited_code_0
     *
     * @mbggenerated
     */
    int insert(InvitedCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invited_code_0
     *
     * @mbggenerated
     */
    int insertSelective(InvitedCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invited_code_0
     *
     * @mbggenerated
     */
    InvitedCode selectByPrimaryKey(InvitedCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invited_code_0
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(InvitedCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table invited_code_0
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(InvitedCode record);
    
    
    /**
     * 通过code查询code信息，注意这里有发表，所以参数是一个invitedcode model
     * @param record
     * @return
     */
    InvitedCode selectByCode(InvitedCode record);

    /**
     * 给邀请码使用数+1
     * @param record
     */
    void addApplyCountByCode(InvitedCode record);
    
    /**
     * 通过
     * @param record
     * @return
     */
    InvitedCode selectByPlayerIdAndGameIdAndActId(InvitedCode record); 
    
}