package com.dsky.baas.gameinvite.dao;

import com.dsky.baas.gameinvite.model.PointsPool;

public interface PointsPoolMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table points_pool
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table points_pool
     *
     * @mbggenerated
     */
    int insert(PointsPool record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table points_pool
     *
     * @mbggenerated
     */
    int insertSelective(PointsPool record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table points_pool
     *
     * @mbggenerated
     */
    PointsPool selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table points_pool
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PointsPool record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table points_pool
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PointsPool record);
}