package com.dsky.baas.gameinvite.dao;

import org.apache.ibatis.annotations.Param;

import com.dsky.baas.gameinvite.model.PointsLog;

public interface PointsLogMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table points_log_tpl
	 *
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table points_log_tpl
	 *
	 * @mbggenerated
	 */
	int insert(PointsLog record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table points_log_tpl
	 *
	 * @mbggenerated
	 */
	int insertSelective(PointsLog record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table points_log_tpl
	 *
	 * @mbggenerated
	 */
	PointsLog selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table points_log_tpl
	 *
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(PointsLog record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table points_log_tpl
	 *
	 * @mbggenerated
	 */
	int updateByPrimaryKey(PointsLog record);

	// create new daily log table
	int createNewTableIfNotExists(@Param("tableName") String tableName);
}